### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by gleporeNARA** [centic9/CommonCrawlDocumentDownload#11]
Looks like a great project, but I'm having trouble changing the Extensions.java file in order to find different extensions. I couldn't find any documentation for how to accomplish this, and when I change the file and re-run ./gradlew check I get failed most of the time.

Please add documentation for how to alter the Extensions file successfully, and also how to run the code against the oldindex instead of the new one.

**Comment by centic9** [comment]
I added some simple notes as JavaDoc to classes `Extensions` and `MimeTypes` to describe how other file-types can be fetched.

If you then follow the existing description at https://github.com/centic9/CommonCrawlDocumentDownload#adjust-which-files-are-found it should be fairly easy to download other file-extensions or mime-types.
