### ISSUE TITLE
Maximum file size

### ISSUE THREAD

**Issue by ankitmodi1** [centic9/CommonCrawlDocumentDownload#13]
Hello, 
This is an absolute great project. Thanks !
Is there any way to download file sizes greater than 2.0M ? We need it for our internal project.

Warm Regards !

**Comment by centic9** [comment]
I don't think there is any such limitation in my project, so if you see only files that are smaller than that then it is likely a limit imposed by CommonCrawl itself, which means this tool cannot do anything about it as far as I see. 

Please reopen with more details if this is not the case.
